when:
  - event: cron
  - event: manual

steps:
  renovate:
    image: renovate/renovate:latest
    environment:
      RENOVATE_TOKEN:
        from_secret: renovate_token
      RENOVATE_CONFIG_FILE: renovate/config.js
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - renovate
